type: "transformation"
version: "1.0"
pipeline:
  components:
    Customer Table:
      type: "table-input"
      parameters:
        componentName: "Customer Table"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "Customer"
        columnNames:
        - "Customer_id"
        - "name"
        - "email"
        - "city"
        - "join_date"
        timeOffset:
    Product:
      type: "table-input"
      parameters:
        componentName: "Product"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "Product"
        columnNames:
        - "product_id"
        - "product_name"
        - "category"
        - "cost"
        timeOffset:
    Sales:
      type: "table-input"
      parameters:
        componentName: "Sales"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "Sales"
        columnNames:
        - "slae_id"
        - "customer_id"
        - "product_id"
        - "quantity"
        - "price"
        - "sale_date"
        timeOffset:
    Customer Filtered data:
      type: "filter"
      sources:
      - "Customer Table"
      parameters:
        componentName: "Customer Filtered data"
        filterConditions:
        - - "Customer_id"
          - "Not"
          - "Null"
          - ""
        - - "name"
          - "Not"
          - "Null"
          - ""
        - - "email"
          - "Not"
          - "Null"
          - ""
        - - "city"
          - "Not"
          - "Null"
          - ""
        - - "join_date"
          - "Not"
          - "Null"
          - ""
        combineCondition: "And"
    'Product Filtered ':
      type: "filter"
      sources:
      - "Product"
      parameters:
        componentName: "Product Filtered "
        filterConditions:
        - - "product_id"
          - "Not"
          - "Null"
          - ""
        - - "product_name"
          - "Not"
          - "Null"
          - ""
        - - "category"
          - "Not"
          - "Null"
          - ""
        - - "cost"
          - "Not"
          - "Null"
          - ""
        combineCondition: "And"
    Sales_Filtered:
      type: "filter"
      sources:
      - "Sales"
      parameters:
        componentName: "Sales_Filtered"
        filterConditions:
        - - "slae_id"
          - "Not"
          - "Null"
          - ""
        - - "customer_id"
          - "Not"
          - "Null"
          - ""
        - - "product_id"
          - "Not"
          - "Null"
          - ""
        - - "quantity"
          - "Not"
          - "Null"
          - ""
        - - "price"
          - "Not"
          - "Null"
          - ""
        - - "sale_date"
          - "Not"
          - "Null"
          - ""
        combineCondition: "And"
    Cusotmer Calculator:
      type: "calculator"
      sources:
      - "Customer Filtered data"
      parameters:
        componentName: "Cusotmer Calculator"
        includeInputColumns: "No"
        calculations:
        - - "\"Customer_id\""
          - "Customer Id"
        - - "\"name\""
          - "Name"
        - - "\"email\""
          - "Email Id"
        - - "\"city\""
          - "Region"
        - - "\"join_date\""
          - "Join Date"
    Product Calculator:
      type: "calculator"
      sources:
      - "Product Filtered "
      parameters:
        componentName: "Product Calculator"
        includeInputColumns: "No"
        calculations:
        - - "\"product_id\""
          - "Product ID"
        - - "\"product_name\""
          - "Product- Name"
        - - "\"category\""
          - "Category"
        - - "\"cost\""
          - "Cost"
    Sales Calculator:
      type: "calculator"
      sources:
      - "Sales_Filtered"
      parameters:
        componentName: "Sales Calculator"
        includeInputColumns: "No"
        calculations:
        - - "\"slae_id\""
          - "Sale Id"
        - - "\"customer_id\""
          - "Customer Id"
        - - "\"product_id\""
          - "Product Id"
        - - "\"quantity\""
          - "Quantity"
        - - "\"price\""
          - "Unit Price"
        - - "\"sale_date\""
          - "Sale Date"
    Join:
      type: "join"
      sources:
      - "Cusotmer Calculator"
      - "Sales Calculator"
      - "Product Calculator"
      parameters:
        componentName: "Join"
        mainTable: "Sales Calculator"
        mainTableAlias: "S"
        joins:
        - - "Cusotmer Calculator"
          - "C"
          - "Left"
        - - "Product Calculator"
          - "P"
          - "Left"
        joinExpressions:
        - - "\"S\".\"Customer Id\"=\"C\".\"Customer Id\""
          - "S_Left_C"
        - - "\"S\".\"Product Id\"=\"P\".\"Product ID\""
          - "S_Left_P"
        columnMappings:
        - - "P.Product- Name"
          - "Product- Name"
        - - "P.Category"
          - "Category"
        - - "P.Cost"
          - "Cost"
        - - "S.Sale Id"
          - "Sale Id"
        - - "S.Product Id"
          - "Product Id"
        - - "S.Quantity"
          - "Quantity"
        - - "S.Unit Price"
          - "Unit Price"
        - - "S.Sale Date"
          - "Sale_Date"
        - - "C.Customer Id"
          - "C_Customer Id"
        - - "C.Name"
          - "Name"
        - - "C.Email Id"
          - "Email Id"
        - - "C.Region"
          - "Region"
        - - "C.Join Date"
          - "Join Date"
    Calculator:
      type: "calculator"
      sources:
      - "Join"
      parameters:
        componentName: "Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "\"Quantity\"*\"Unit Price\""
          - "Total Amount"
        - - "\"Unit Price\"-\"Cost\""
          - "Profit Margine"
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "Calculator"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "sales_fact_one"
        orderBy:
        - - "Join Date"
          - "ASCENDING"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Customer Table:
      position:
        x: -200
        "y": 40
      tempMetlId: 1
    Product:
      position:
        x: -210
        "y": -290
      tempMetlId: 4
    Sales:
      position:
        x: -220
        "y": -140
      tempMetlId: 5
    Customer Filtered data:
      position:
        x: -50
        "y": 40
      tempMetlId: 2
    'Product Filtered ':
      position:
        x: -50
        "y": -290
      tempMetlId: 8
    Sales_Filtered:
      position:
        x: -50
        "y": -140
      tempMetlId: 11
    Cusotmer Calculator:
      position:
        x: 100
        "y": 40
      tempMetlId: 7
    Product Calculator:
      position:
        x: 120
        "y": -290
      tempMetlId: 9
    Sales Calculator:
      position:
        x: 120
        "y": -140
      tempMetlId: 12
    Join:
      position:
        x: 590
        "y": -140
      tempMetlId: 14
    Calculator:
      position:
        x: 750
        "y": -140
      tempMetlId: 15
    Rewrite Table:
      position:
        x: 910
        "y": -140
      tempMetlId: 16
