type: "transformation"
version: "1.0"
pipeline:
  components:
    Join:
      type: "join"
      sources:
      - "Cleaned Customer"
      - "Cleaned Sales"
      parameters:
        componentName: "Join"
        mainTable: "Cleaned Sales"
        mainTableAlias: "Sales"
        joins:
        - - "Cleaned Customer"
          - "Customer"
          - "Left"
        joinExpressions:
        - - "\"Sales\".\"Customer Id\"=\"Customer\".\"Customer Id\""
          - "Sales_Left_Customer"
        columnMappings:
        - - "Sales.Sale Id"
          - "Sale Id"
        - - "Sales.Customer Id"
          - "Sales_Customer Id"
        - - "Sales.Product Id"
          - "Product Id"
        - - "Sales.Quantity"
          - "Quantity"
        - - "Sales.Price"
          - "Price"
        - - "Sales.Sale Date"
          - "Sale Date"
        - - "Customer.Customer Id"
          - "Customer_Customer Id"
        - - "Customer.Name"
          - "Name"
        - - "Customer.Email Id"
          - "Email Id"
        - - "Customer.City"
          - "City"
        - - "Customer.Join Date"
          - "Join Date"
    Cleaned Customer:
      type: "table-input"
      parameters:
        componentName: "Cleaned Customer"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "Cleaned Customer"
        columnNames:
        - "Customer Id"
        - "Name"
        - "Email Id"
        - "City"
        - "Join Date"
        timeOffset:
    Cleaned Sales:
      type: "table-input"
      parameters:
        componentName: "Cleaned Sales"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "Cleaned Sales"
        columnNames:
        - "Sale Id"
        - "Customer Id"
        - "Product Id"
        - "Quantity"
        - "Price"
        - "Sale Date"
        timeOffset:
    Join 2:
      type: "join"
      sources:
      - "Join"
      - "Cleaned Product"
      parameters:
        componentName: "Join 2"
        mainTable: "Join"
        mainTableAlias: "Combine"
        joins:
        - - "Cleaned Product"
          - "Product"
          - "Left"
        joinExpressions:
        - - "\"Combine\".\"Product Id\"=\"Product\".\"Product ID\""
          - "Combine_Left_Product"
        columnMappings:
        - - "Combine.Join Date"
          - "Join Date"
        - - "Combine.Sales_Customer Id"
          - "Customer Id"
        - - "Combine.Name"
          - "Name"
        - - "Combine.Email Id"
          - "Email Id"
        - - "Combine.City"
          - "City"
        - - "Combine.Product Id"
          - "Product Id"
        - - "Product.Category"
          - "Category"
        - - "Product.Product- Name"
          - "Product- Name"
        - - "Combine.Sale Date"
          - "Sale Date"
        - - "Combine.Sale Id"
          - "Sale Id"
        - - "Product.Cost"
          - "Cost"
        - - "Combine.Quantity"
          - "Quantity"
        - - "Combine.Price"
          - "Price"
    Cleaned Product:
      type: "table-input"
      parameters:
        componentName: "Cleaned Product"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "Cleaned Product"
        columnNames:
        - "Product ID"
        - "Product- Name"
        - "Category"
        - "Cost"
        timeOffset:
    Calculator:
      type: "calculator"
      sources:
      - "Join 2"
      parameters:
        componentName: "Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "\"Quantity\"*\"Cost\""
          - "Total Sale Amount"
        - - "\"Price\"*\"Quantity\""
          - "Profit Margine"
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "Calculator"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "Sales_fact"
        orderBy:
        - - "Sale Date"
          - "ASCENDING"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Join:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Cleaned Customer:
      position:
        x: -160
        "y": 0
      tempMetlId: 2
    Cleaned Sales:
      position:
        x: -160
        "y": 120
      tempMetlId: 4
    Join 2:
      position:
        x: 160
        "y": 0
      tempMetlId: 5
    Cleaned Product:
      position:
        x: 0
        "y": -120
      tempMetlId: 6
    Calculator:
      position:
        x: 320
        "y": 0
      tempMetlId: 7
    Rewrite Table:
      position:
        x: 480
        "y": 0
      tempMetlId: 8
